{% set name = "load-atoms" %}
{% set version = "0.3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/load_atoms-{{ version }}.tar.gz
  sha256: 0ee87648d8515ff7c296c87f162a762828407156083ac6baba9e554fd4044296

build:
  entry_points:
    - load-atoms = load_atoms.scripts.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools >=61.0.0
    - wheel
  run:
    - ase
    - h5py
    - ipywidgets
    - numpy
    - pydantic >2.0.0
    - python >={{ python_min }}
    - python-lmdb
    - pyyaml
    - requests
    - rich

test:
  imports:
    - load_atoms
  commands:
    - pip check
    - load-atoms --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://jla-gardner.github.io/load-atoms/
  dev_url: https://github.com/jla-gardner/load-atoms
  summary: Large Open Access Datasets for Atomistic Materials Science (LOAD-AtoMS)
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - awvwgk
